# Step 1 


In [1]:
import os
import shutil
import mimetypes
import csv

lista_files=[]


my_path=("files")
dirs = os.listdir( my_path )

for file in dirs: #estraggo i file uno per uno
    if file.endswith(".mp3") or file.endswith(".png") or file.endswith(".jpeg")or file.endswith(".jpg")or file.endswith(".odt")or file.endswith(".txt"):
        f_path = os.path.join("files", file) #punto la posizione del file in questione
        f_size = os.path.getsize(f_path)#estraggo la Size
        type_file=mimetypes.guess_type(f_path) #estraggo il tipo di file
        print(f"{os.path.basename(f_path)},{type_file}, {f_size} Kbyte") # stampo le informazioni estratte
        name = os.path.basename(f_path)
        size = f_size
        type_info = type_file
        lista_files.extend((name, size, type_info))# aggiungo le informazioni alla mia lista

info_files = tuple(lista_files[n:n + 3] for n, i in enumerate(lista_files) if n % 3 == 0) #separo le informazioni per file


if os.path.isfile("files/recap.csv"):
    with open("files/recap.csv","a") as out:
        csv_out=csv.writer(out)#per scrivere in un file csv usiamo la funzione csv.writer
        for row in info_files:   
            csv_out.writerow(row)
else: 
    with open("files/recap.csv","a") as out:
        csv_out=csv.writer(out)#per scrivere in un file csv usiamo la funzione csv.writer
        csv_out.writerow(['name','byteSize','Type_info'])#scrivo la prima riga
        for row in info_files:
            csv_out.writerow(row)

for file in dirs:
    if os.path.isdir("files/audio/")==False: # verifico l'esistenza delle cartelle
        os.mkdir("files/audio")
    if os.path.isdir("files/docs/")==False:
        os.mkdir("files/docs")
    if os.path.isdir("files/images/")==False:
        os.mkdir("files/images")
    if file.endswith(".mp3") or file.endswith(".wav"): #verifico l'estensione dei file
        shutil.move(os.path.join("files",file),os.path.join("files/audio/",file))#sposto i files nella sottocartella corretta
    if file.endswith(".txt") or file.endswith(".odt"):
        shutil.move(os.path.join("files/",file),os.path.join("files/docs/",file))
    if file.endswith(".png") or file.endswith(".jpg")or file.endswith(".jpeg"):
        shutil.move(os.path.join("files/",file),os.path.join("files/images/",file))






song1.mp3,('audio/mpeg', None), 1087849 Kbyte
ciao.txt,('text/plain', None), 12 Kbyte
song2.mp3,('audio/mpeg', None), 764176 Kbyte
daffodil.jpg,('image/jpeg', None), 24657 Kbyte
trump.jpeg,('image/jpeg', None), 10195 Kbyte
bw.png,('image/png', None), 94926 Kbyte
pippo.odt,('application/vnd.oasis.opendocument.text', None), 8299 Kbyte
eclipse.png,('image/png', None), 64243 Kbyte


# Step 3

In [2]:
import os
import numpy as np
from tabulate import tabulate
from PIL import Image
from numpy import asarray
import matplotlib


for filenames in os.listdir("files/images"):
    if filenames.endswith(".png") or filenames.endswith(".jpg")or filenames.endswith(".jpeg"): 
        image = np.array(Image.open('files/images/' + filenames)) #apro le immagini 
        valori= np.mean(image, axis=(0, 1))
        print("")
        if valori.size==1:
            print ("  Immagine in scala di grigio")
        if valori.size==3:
            print ("  Immagine RGB")
        if valori.size==4:
            print ("  Immagine RGBA")
        
        #stampo con tabulate i dati richiesti, indicando, sia con i valori che con un messaggio, il tipo di img
        print(tabulate([[filenames],[image.ndim],[image.shape],[np.mean(image, axis=(0, 1)),]],tablefmt='orgtbl'))



  Immagine RGB
| daffodil.jpg                             |
| 3                                        |
| (500, 335, 3)                            |
| [109.25114627  85.55517612   4.96728955] |

  Immagine RGB
| trump.jpeg                            |
| 3                                     |
| (183, 275, 3)                         |
| [97.01080974 98.99407849 90.92379533] |

  Immagine in scala di grigio
| bw.png             |
| 2                  |
| (512, 512)         |
| 21.480064392089844 |

  Immagine RGBA
| eclipse.png                                           |
| 3                                                     |
| (256, 256, 4)                                         |
| [109.04953003 109.52186584  39.84899902 133.59094238] |
